spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=srithan06@gmail.com
spring.mail.password=cico pubb bycu udzb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true